display_information:
  name: Pair Programming Bot
  description: Matches developers for pair programming sessions
  background_color: "#2c2d30"

features:
  bot_user:
    display_name: Pair Programming Bot
    always_online: true

oauth_config:
  scopes:
    bot:
      - chat:write
      - im:write
      - groups:write
      - channels:read
      - users:read

settings:
  interactivity:
    is_enabled: true
    request_url: https://YOUR-RENDER-URL/api/slack/action
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false