services:
  - type: web
    name: pair-programming-bot
    runtime: ruby
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec rackup config.ru -p $PORT -o 0.0.0.0
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SLACK_CLIENT_ID
        sync: false
      - key: SLACK_CLIENT_SECRET
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: SLACK_OAUTH_SCOPE
        value: chat:write,im:write,groups:write,channels:read,users:read
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: PAIR_PROGRAMMING_CHANNEL_ID
        sync: false
      - key: RACK_ENV
        value: production